---
new_page_extension: md
auto_deploy: false
admin_path: Y-C-Dev-team files
webhook_url: "/nuruddeen"
sections:
- type: directory
  path: 'Y-C Dev team '
  label: Y-c-dev-package
  create: all
  match: "/thelight3"
  new_doc_ext: theligh3)
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
